### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by remisublette** [INFO523-S24/project-final-datadetectives#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

@h-akston Maksim Kulik 
@remisublette Remi Hendershott 
@suryavardhandama Surya Vardhan Dama 
@Sailaasya-1 Gorantla Sai Laasya
@KommareddyMonicaTejaswi Monica Tejaswi Kommareddy
@xinformatics Shashank Yadav
@Priom1996 Priom Mahmud 

- Describe the goal of the project.
The goal of this project is to analyze the complex relationships between economic and population growth, sustainable energy practices, and energy consumption.

- Describe the data used or collected.
The data is about global energy trends and contains one csv file. They got their data from Our World in Data (OWID), a renowned institution acknowledged for its meticulous, evidence-based study on global matters.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Q1 will be approached with the standard data cleaning preparation and analysis. They mention that they will perform correlation analysis, time series, regression, and multiple regression. They will then visualize their results through a variety of methods, including line graphs, scatter plots, bar, and pie charts. For Q2, a similar process to start with cleaning and EDA, but they plan on analyzing their data this time by descriptive statistics and regression analysis. They will visualize Q2 with maps, line graphs, and density plots. 

- Is there anything that is unclear from the proposal?
The descriptions of the columns are unclear in terms of the date range of the population column, we just found the range to be curious. From what we can see in their data, there are no values from 10,000 BCE so we are just wondering what the date range is.

- Provide constructive feedback on how the team might be able to improve their project.
The display of the dataset doesn't show any values, perhaps they could do data sample instead of head, which would output random values and possibly provide more context about the data for the reader. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation?
It will be cool to see which countries are moving towards the trajectory of relying more on renewable energy and producing less greenhouse gas emissions. 

- Provide constructive feedback on any issues with file and/or code organization.
Nothing other than the point we mentioned above about how the display of the dataset doesn't show any values, perhaps they could do data sample instead of head, which would output random values and possibly provide more context about the data for the reader. Other than that they are very organized and looks good!

- (Optional) Any further comments or feedback?
 Typo under dataset description: says "gross domestic project" but project should be "product".

**Comment by ayeshakhatunsujana** [comment]
Hello Peer Review Team,
As you have mentioned, We have already working on more detailed descriptions of our analysis techniques and incorporating specific examples or case studies to illustrate our approach. Not only that, we have added some equations to make it more clear about the analysis. We have already worked on the data cleaning process too. However, we have included the summary of the main variables in the dataset. The typos are already fixed. Finally, we must say that we really appreciate your constructive feedback. 

Best Regards
Data Detectives Team
