### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by rxnsh** [INFO523-S24/project-final-datadetectives#2]
The following is the peer review of the project proposal by MiningMinds. The team members that participated in this review are 

- Roxana Akbarsharifi- @rxnsh
- Omid Zandi - @zandi-omid
- Deema Albluwi - @dee-koudz
- Gowtham Gopalakrishnan - @Gowtham-18
- Nandhini Anne - @NandhiniAnne
- Sai Navya Reddy Busireddy - @navyareddy152

- Describe the goal of the project.

The goal of the project is to analyze the complex relationships between economic and population growth, sustainable energy practices, and energy consumption.

- Describe the data used or collected.

The team is using the Our World in Data Energy dataset, which contains information on energy consumption, GDP, population, and more for various regions around the world. 

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

To answer the research questions, the team plans to employ various methods including data cleaning, feature engineering, exploratory data analysis, regression analysis, and data visualization. 

- Is there anything that is unclear from the proposal?

The proposal provides a clear outline of the project goals, dataset, research questions, and planned methodologies. However, it could benefit from more detailed descriptions of specific analysis techniques and how external data will be integrated.

- Provide constructive feedback on how the team might be able to improve their project.

The team could improve the project by providing more detailed descriptions of their analysis techniques and incorporating specific examples or case studies to illustrate their approach.  they could consider discussing potential challenges or limitations of their methods and how they plan to address them.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

In addition to predicting power consumption and identifying countries practicing sustainable energy practices, we're keen on investigating which countries have made the most progress in this regard. 

We are also interested in seeing the results of the regression analysis and data visualization techniques, and relationships between variables.

- Provide constructive feedback on any issues with file and/or code organization.

Many values in the displayed dataset are marked as 'NaN'. They can ensure that the data is cleaned before displaying it on the website. This will help avoid confusion among users and ensure that the data presented is accurate and meaningful.

They could use more inline code for dataset overview. 

It could be beneficial to include a summary of the main variables/features in the dataset. 

What makes this dataset particularly relevant or interesting for the research questions being posed?

The plan for Answering Questions could be more structured and detailed. For example, explicitly listing the steps involved in data cleaning, feature engineering, exploratory data analysis, regression analysis, etc., would provide a clearer roadmap for the project.

It would be helpful to specify what kinds of external data might be relevant and how they would be incorporated into the analysis.
 
About the Project Timeline, Maybe they should consider more time for working on "Building an interactive Python Visualization Dashboard using Panel".

- (Optional) Any further comments or feedback?

**Comment by ayeshakhatunsujana** [comment]
Dear  MiningMinds Team, 
As you have mentioned, We have already working on more detailed descriptions of our analysis techniques and incorporating specific examples or case studies to illustrate our approach. Not only that, we have added some equations to make it more clear about the analysis. We have already worked on the data cleaning process too. However, we have included the summary of the main variables in the dataset. Finally, we must say that we really appreciate your constructive feedback. 

Best Regards

Data Detectives Team
