### ISSUE TITLE
Presentation peer review by KG Competitors

### ISSUE THREAD

**Issue by remisublette** [INFO523-S24/project-final-datadetectives#6]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

@h-akston Maksim Kulik
@remisublette Remi Hendershott
@suryavardhandama Surya Vardhan Dama
@Sailaasya-1 Gorantla Sai Laasya
@KommareddyMonicaTejaswi Monica Tejaswi Kommareddy
@xinformatics Shashank Yadav
@Priom1996 Priom Mahmud

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes, the two research questions were well designed and the data they selected was indeed relevant to answer their questions. For example they wanted to know if it possible to predict a nation’s power consumption by considering its population size, gross domestic product (GDP), and the percentage of electricity generated from renewable sources so they used csv data files corresponding to population, gdp, and electricity levels of renewables to seek their answer. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Yes they did, they had scatter plots, time series, bar plots, as well as a heat map. Their visuals were great and clean and explained well by the members. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

It was well thought out and a lot of effort clearly went into it. Yes they considered their limitations and had a very clean and easy to follow presentation. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

Yes, the slides were clean, readable, and had great visuals with labels and everything. 10 out 10!

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
 They presented well as a team for the most part. They did have meaningful comments and stuck to time pretty well!

**Comment by rlyalyther** [comment]
Thank you for reviewing our presentation and providing great feedback!
